### ISSUE TITLE
I am unable to run the app

### ISSUE THREAD

**Issue by ipx403** [dev-null2019/pwnaflipper#1]
I open the "esp32 CAMERA" app and then "waiting esp32 cam" There's nothing else.

**Comment by ipx403** [comment]
![20240312012629](https://github.com/dev-null2019/pwnaflipper/assets/52273498/cf82448e-3fde-4b93-8cab-9a0e28188aad)

help me~

**Comment by ipx403** [comment]
I have already turned on the 5V power button of Flipperzero, and the plugin is also enabled in pwnagotchi. After debugging, it was confirmed that/dev/serial0 was turned on. Can you help me? I have been confused for a long time~

**Comment by dev-null2019** [comment]
Which firmware do you have on your flipper? It seems that in some esp32 camera apps the 5V pin is not turned on.
On Roguemaster the "[CAM] Camera v1.0" app works!
I currently write a flipper application that turns on the 5V and displays the Pwnagotchi image.

**Comment by ipx403** [comment]
I also use the Roguemaster the "[CAM] Camera v1.0" app, and I have also opened the 5V pin, but it still does not display the pwn.  I would like to ask how you set up the pwn.  I opened your plugin on the web page and set the port to /dev/serial0. Initially, I successfully tested it twice in the project https://github.com/Matt-London/pwnagotchi-flipper/, but then it did not display anymore.  After that, I discovered your project.  Please guide me again on how to set up the pwn. Also, I look forward to your app.

**Comment by ipx403** [comment]
> Which firmware do you have on your flipper? It seems that in some esp32 camera apps the 5V pin is not turned on. On Roguemaster the "[CAM] Camera v1.0" app works! I currently write a flipper application that turns on the 5V and displays the Pwnagotchi image.

I succeeded. The reason for the previous failure was that I did not enable the external display in config, but after successful display, the screen was too large. Does this "dummydisplay. py" file need to be run every time it is turned on? Thank you!

**Comment by ipx403** [comment]
I understand now, I just need to modify the display type to "dummydisplay". Sorry, I'm a new, it turns out GitHub can still do this....
